[package]
name = "drug_use_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rusqlite = "0.29.0"
sysinfo = "0.29.0"

[dev-dependencies]
tempfile = "3.2"